<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1071" started-at="2020-09-25T11:34:49 CDT" finished-at="2020-09-25T11:34:51 CDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1071" started-at="2020-09-25T11:34:49 CDT" finished-at="2020-09-25T11:34:51 CDT">
      <class name="com.hrms.testcases.FiveEmployees">
        <test-method status="PASS" signature="generateReport()[pri:0, instance:com.hrms.testcases.FiveEmployees@536aaa8d]" name="generateReport" is-config="true" duration-ms="153" started-at="2020-09-25T11:34:49 CDT" finished-at="2020-09-25T11:34:50 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReport -->
        <test-method status="SKIP" signature="loginCredentials(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.hrms.testcases.FiveEmployees@536aaa8d]" name="loginCredentials" duration-ms="0" started-at="2020-09-25T11:34:51 CDT" data-provider="getDataExcel" finished-at="2020-09-25T11:34:51 CDT">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:51)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:147)
at org.testng.internal.Parameters.handleParameters(Parameters.java:801)
at org.testng.internal.Parameters.handleParameters(Parameters.java:744)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:783)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at com.hrms.utils.ExcelUtility.getCellData(ExcelUtility.java:50)
at com.hrms.utils.ExcelUtility.excelToArray2(ExcelUtility.java:78)
at com.hrms.testcases.FiveEmployees.getDataExcel(FiveEmployees.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:78)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:47)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginCredentials -->
        <test-method status="PASS" signature="writeReport()[pri:0, instance:com.hrms.testcases.FiveEmployees@536aaa8d]" name="writeReport" is-config="true" duration-ms="3" started-at="2020-09-25T11:34:51 CDT" finished-at="2020-09-25T11:34:51 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeReport -->
      </class> <!-- com.hrms.testcases.FiveEmployees -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
